name = "Dumper"
uuid = "e5784763-3d25-4a95-96c2-15edcf1d1c66"
authors = ["Alex Wietek <awietek@pks.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
